from pathlib import Path

from fastapi import Depends
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from agents.manager_agent import ManagerAgent
from agents.publisher_agent import PublisherAgent
from agents.research_agent import ResearchAgent
from agents.seo_agent import SEOAgent
from agents.script_agent import ScriptAgent
from agents.subtitle_agent import SubtitleAgent
from agents.thumbnail_agent import ThumbnailAgent
from agents.trend_agent import TrendAgent
from agents.video_agent import VideoAgent
from agents.voice_agent import VoiceAgent
from backend.main import app, get_manager_agent
from database.database import SessionLocal, get_db
from database.models import Audio, PublishJob, Script, Topic, TopicStatus, Video
from services.ffmpeg_service import FFmpegService
from services.google_trends_service import GoogleTrendsService
from services.image_service import ImageService
from services.publisher_decision_service import PublisherDecisionResult, PublisherDecisionService
from services.reddit_service import RedditService
from services.subtitle_service import SubtitleService
from services.thumbnail_service import ThumbnailService
from services.tts_service import TTSService
from services.viral_prediction_service import ViralPredictionResult, ViralPredictionService
from services.youtube_service import YouTubeService, YouTubeUploadResult
from tests.fake_llm import FakeLLMService


class FakeYouTubeService(YouTubeService):
    def upload_video(
        self,
        video_path: str,
        title: str = "AI Short",
        description: str = "Generated by social-media-ai.",
        tags: list[str] | None = None,
        privacy_status: str = "private",
        thumbnail_path: str | None = None,
        category_id: str = "22",
        publish_at: str | None = None,
    ) -> YouTubeUploadResult:
        return YouTubeUploadResult(
            youtube_video_id="youtube-test-id",
            youtube_url="https://www.youtube.com/watch?v=youtube-test-id",
            thumbnail_url="https://img.youtube.com/vi/youtube-test-id/maxresdefault.jpg",
            published_at="2026-07-01T00:00:00+00:00",
            upload_time=1.2,
            processing_status="processing",
            progress=100,
        )


class FailingYouTubeService(YouTubeService):
    def upload_video(
        self,
        video_path: str,
        title: str = "AI Short",
        description: str = "Generated by social-media-ai.",
        tags: list[str] | None = None,
        privacy_status: str = "private",
        thumbnail_path: str | None = None,
        category_id: str = "22",
        publish_at: str | None = None,
    ) -> YouTubeUploadResult:
        raise RuntimeError("youtube unavailable")


def override_manager_agent(db: Session = Depends(get_db)) -> ManagerAgent:
    return ManagerAgent(
        db=db,
        trend_agent=TrendAgent(
            reddit_service=RedditService(),
            google_trends_service=GoogleTrendsService(),
        ),
        research_agent=ResearchAgent(llm_service=FakeLLMService()),
        script_agent=ScriptAgent(llm_service=FakeLLMService()),
        voice_agent=VoiceAgent(db=db, tts_service=TTSService()),
        video_agent=VideoAgent(
            db=db,
            ffmpeg_service=FFmpegService(),
            image_service=ImageService(),
        ),
        subtitle_agent=SubtitleAgent(db=db, subtitle_service=SubtitleService()),
        seo_agent=SEOAgent(db=db, llm_service=FakeLLMService()),
        thumbnail_agent=ThumbnailAgent(db=db, thumbnail_service=ThumbnailService()),
        publisher_agent=PublisherAgent(db=db, youtube_service=FakeYouTubeService()),
    )


def create_video(video_path: str) -> Video:
    Path(video_path).parent.mkdir(parents=True, exist_ok=True)
    Path(video_path).write_bytes(b"fake-mp4")

    db = SessionLocal()
    try:
        topic = Topic(title="AI Tools", score=90, status=TopicStatus.SCRIPTED)
        script = Script(topic=topic, content="Short script.")
        audio = Audio(script=script, path="storage/audio/publish_test_audio.mp3")
        video = Video(audio=audio, path=video_path)
        db.add(video)
        db.commit()
        db.refresh(video)
        return video
    finally:
        db.close()


def viral_prediction(score: int) -> ViralPredictionResult:
    return ViralPredictionResult(
        viral_score=score,
        predicted_ctr=score,
        predicted_retention=score,
        shareability="High" if score >= 90 else "Medium",
        uniqueness="High",
        competition="Medium",
        emotion="curiosity",
        risk_level="Low" if score >= 80 else "High",
        confidence=85,
        publish_recommendation=score >= 80,
        reasons=["strong hook"],
        improvements=["tighten thumbnail"],
        analysis_timestamp="2026-06-30T00:00:00+00:00",
        fallback_used=False,
    )


def publisher_decision(score: int) -> PublisherDecisionResult:
    return PublisherDecisionResult(
        publish=score >= 80,
        confidence=86,
        overall_score=score,
        expected_views=2500 if score >= 80 else 300,
        expected_ctr=score,
        expected_retention=score,
        risk_level="Low" if score >= 90 else "High",
        strengths=["strong package"],
        weaknesses=["minor risk"],
        improvements=["tighten title"],
        recommended_publish_time="18:00",
        recommended_day="Friday",
        reasoning="Publisher decision test.",
        analysis_timestamp="2026-06-30T00:00:00+00:00",
        fallback_used=False,
    )


def test_publish_youtube() -> None:
    app.dependency_overrides[get_manager_agent] = override_manager_agent
    try:
        with TestClient(app) as client:
            video = create_video("storage/videos/publish_test_video.mp4")
            response = client.post("/publish-youtube", json={"video_id": video.id})

        assert response.status_code == 200
        assert response.json() == {
            "status": "uploaded",
            "youtube_url": "https://www.youtube.com/watch?v=youtube-test-id",
        }

        db = SessionLocal()
        try:
            publish_job = db.query(PublishJob).filter(PublishJob.video_id == video.id).one()
            assert publish_job.platform == "youtube"
            assert publish_job.youtube_video_id == "youtube-test-id"
            assert publish_job.youtube_url == "https://www.youtube.com/watch?v=youtube-test-id"
        finally:
            db.close()
    finally:
        app.dependency_overrides.clear()


def test_publish_youtube_returns_404_for_missing_video() -> None:
    app.dependency_overrides[get_manager_agent] = override_manager_agent
    try:
        with TestClient(app) as client:
            response = client.post("/publish-youtube", json={"video_id": 999999})

        assert response.status_code == 404
        assert response.json()["detail"] == "Video 999999 was not found"
    finally:
        app.dependency_overrides.clear()


def test_publisher_agent_runs_viral_prediction_before_upload() -> None:
    video = create_video("storage/videos/publish_prediction_video.mp4")
    llm = FakeLLMService(viral_prediction=viral_prediction(91))
    db = SessionLocal()
    try:
        agent = PublisherAgent(
            db=db,
            youtube_service=FakeYouTubeService(),
            viral_prediction_service=ViralPredictionService(llm),
        )
        job = agent.publish_youtube(video_id=video.id)

        metadata = agent.metadata_service.load_viral_prediction(video.id)
        assert job.youtube_video_id == "youtube-test-id"
        assert llm.viral_prediction_called is True
        assert metadata["viral_score"] == 91
        assert metadata["publish_recommendation"] is True
    finally:
        db.close()


def test_publisher_agent_preserves_publish_when_prediction_is_low() -> None:
    video = create_video("storage/videos/publish_low_prediction_video.mp4")
    llm = FakeLLMService(viral_prediction=viral_prediction(72))
    db = SessionLocal()
    try:
        agent = PublisherAgent(
            db=db,
            youtube_service=FakeYouTubeService(),
            viral_prediction_service=ViralPredictionService(llm),
        )
        job = agent.publish_youtube(video_id=video.id)

        metadata = agent.metadata_service.load_viral_prediction(video.id)
        assert job.youtube_video_id == "youtube-test-id"
        assert metadata["viral_score"] == 72
        assert metadata["publish_recommendation"] is False
    finally:
        db.close()


def test_publisher_agent_runs_decision_before_upload() -> None:
    video = create_video("storage/videos/publish_decision_video.mp4")
    llm = FakeLLMService(
        viral_prediction=viral_prediction(91),
        publisher_decision=publisher_decision(92),
    )
    db = SessionLocal()
    try:
        agent = PublisherAgent(
            db=db,
            youtube_service=FakeYouTubeService(),
            viral_prediction_service=ViralPredictionService(llm),
            publisher_decision_service=PublisherDecisionService(llm),
        )
        job = agent.publish_youtube(video_id=video.id)

        metadata = agent.metadata_service.load_publisher_decision(video.id)
        assert job.youtube_video_id == "youtube-test-id"
        assert llm.viral_prediction_called is True
        assert llm.publisher_decision_called is True
        assert metadata["overall_score"] == 92
        assert metadata["publish"] is True
        assert metadata["expected_ctr"] == 92
    finally:
        db.close()


def test_publisher_agent_records_failed_job_when_upload_fails() -> None:
    video = create_video("storage/videos/publish_failed_upload_video.mp4")
    db = SessionLocal()
    try:
        agent = PublisherAgent(
            db=db,
            youtube_service=FailingYouTubeService(),
        )
        job = agent.publish_youtube(video_id=video.id)

        metadata = agent.metadata_service.load_youtube_upload(video.id)
        assert job.status.value == "failed"
        assert job.youtube_video_id is None
        assert metadata["upload_status"] == "failed"
        assert "youtube unavailable" in metadata["error"]
    finally:
        db.close()
