from pathlib import Path

from fastapi import Depends
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from agents.manager_agent import ManagerAgent
from agents.publisher_agent import PublisherAgent
from agents.research_agent import ResearchAgent
from agents.seo_agent import SEOAgent
from agents.script_agent import ScriptAgent
from agents.subtitle_agent import SubtitleAgent
from agents.thumbnail_agent import ThumbnailAgent
from agents.trend_agent import TrendAgent
from agents.video_agent import VideoAgent
from agents.voice_agent import VoiceAgent
from backend.main import app, get_manager_agent
from database.database import SessionLocal, get_db
from database.models import Audio, PublishJob, Script, Topic, TopicStatus, Video
from services.ffmpeg_service import FFmpegService
from services.google_trends_service import GoogleTrendsService
from services.image_service import ImageService
from services.reddit_service import RedditService
from services.subtitle_service import SubtitleService
from services.thumbnail_service import ThumbnailService
from services.tts_service import TTSService
from services.youtube_service import YouTubeService, YouTubeUploadResult
from tests.fake_llm import FakeLLMService


class FakeYouTubeService(YouTubeService):
    def upload_video(
        self,
        video_path: str,
        title: str = "AI Short",
        description: str = "Generated by social-media-ai.",
        tags: list[str] | None = None,
        privacy_status: str = "private",
    ) -> YouTubeUploadResult:
        return YouTubeUploadResult(
            youtube_video_id="youtube-test-id",
            youtube_url="https://www.youtube.com/watch?v=youtube-test-id",
        )


def override_manager_agent(db: Session = Depends(get_db)) -> ManagerAgent:
    return ManagerAgent(
        db=db,
        trend_agent=TrendAgent(
            reddit_service=RedditService(),
            google_trends_service=GoogleTrendsService(),
        ),
        research_agent=ResearchAgent(llm_service=FakeLLMService()),
        script_agent=ScriptAgent(llm_service=FakeLLMService()),
        voice_agent=VoiceAgent(db=db, tts_service=TTSService()),
        video_agent=VideoAgent(
            db=db,
            ffmpeg_service=FFmpegService(),
            image_service=ImageService(),
        ),
        subtitle_agent=SubtitleAgent(db=db, subtitle_service=SubtitleService()),
        seo_agent=SEOAgent(db=db, llm_service=FakeLLMService()),
        thumbnail_agent=ThumbnailAgent(db=db, thumbnail_service=ThumbnailService()),
        publisher_agent=PublisherAgent(db=db, youtube_service=FakeYouTubeService()),
    )


def create_video(video_path: str) -> Video:
    Path(video_path).parent.mkdir(parents=True, exist_ok=True)
    Path(video_path).write_bytes(b"fake-mp4")

    db = SessionLocal()
    try:
        topic = Topic(title="AI Tools", score=90, status=TopicStatus.SCRIPTED)
        script = Script(topic=topic, content="Short script.")
        audio = Audio(script=script, path="storage/audio/publish_test_audio.mp3")
        video = Video(audio=audio, path=video_path)
        db.add(video)
        db.commit()
        db.refresh(video)
        return video
    finally:
        db.close()


def test_publish_youtube() -> None:
    app.dependency_overrides[get_manager_agent] = override_manager_agent
    try:
        with TestClient(app) as client:
            video = create_video("storage/videos/publish_test_video.mp4")
            response = client.post("/publish-youtube", json={"video_id": video.id})

        assert response.status_code == 200
        assert response.json() == {
            "status": "uploaded",
            "youtube_url": "https://www.youtube.com/watch?v=youtube-test-id",
        }

        db = SessionLocal()
        try:
            publish_job = db.query(PublishJob).filter(PublishJob.video_id == video.id).one()
            assert publish_job.platform == "youtube"
            assert publish_job.youtube_video_id == "youtube-test-id"
            assert publish_job.youtube_url == "https://www.youtube.com/watch?v=youtube-test-id"
        finally:
            db.close()
    finally:
        app.dependency_overrides.clear()


def test_publish_youtube_returns_404_for_missing_video() -> None:
    app.dependency_overrides[get_manager_agent] = override_manager_agent
    try:
        with TestClient(app) as client:
            response = client.post("/publish-youtube", json={"video_id": 999999})

        assert response.status_code == 404
        assert response.json()["detail"] == "Video 999999 was not found"
    finally:
        app.dependency_overrides.clear()
