from dataclasses import dataclass
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from backend.config import get_settings
from services.utils.logging import get_rotating_logger
from services.utils.retry import retry


YOUTUBE_UPLOAD_SCOPE = ["https://www.googleapis.com/auth/youtube.upload"]
publish_logger = get_rotating_logger("publish", "publish.log")


class YouTubeConfigurationError(Exception):
    pass


@dataclass(frozen=True)
class YouTubeUploadResult:
    youtube_video_id: str
    youtube_url: str


class YouTubeService:
    def __init__(self) -> None:
        self.settings = get_settings()

    @retry(max_attempts=3, delays=(30, 120, 300), logger=publish_logger)
    def upload_video(
        self,
        video_path: str,
        title: str = "AI Short",
        description: str = "Generated by social-media-ai.",
        tags: list[str] | None = None,
        privacy_status: str = "private",
    ) -> YouTubeUploadResult:
        tags = tags or ["AI", "Shorts", "Automation"]
        youtube = self._build_client()
        media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")
        request = youtube.videos().insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": title,
                    "description": description,
                    "tags": tags,
                    "categoryId": "22",
                },
                "status": {
                    "privacyStatus": privacy_status,
                    "selfDeclaredMadeForKids": False,
                },
            },
            media_body=media,
        )
        response = request.execute()
        youtube_video_id = response["id"]
        return YouTubeUploadResult(
            youtube_video_id=youtube_video_id,
            youtube_url=f"https://www.youtube.com/watch?v={youtube_video_id}",
        )

    def _build_client(self):
        credentials = self._load_credentials()
        return build("youtube", "v3", credentials=credentials)

    def _load_credentials(self) -> Credentials:
        token_path = Path(self.settings.youtube_token_file)
        client_secrets_path = Path(self.settings.youtube_client_secrets_file)

        credentials = None
        if token_path.exists():
            credentials = Credentials.from_authorized_user_file(str(token_path), YOUTUBE_UPLOAD_SCOPE)

        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
            token_path.parent.mkdir(parents=True, exist_ok=True)
            token_path.write_text(credentials.to_json(), encoding="utf-8")
            return credentials

        if credentials and credentials.valid:
            return credentials

        if not client_secrets_path.exists():
            raise YouTubeConfigurationError(
                f"YouTube client secrets file was not found: {client_secrets_path}"
            )

        flow = InstalledAppFlow.from_client_secrets_file(str(client_secrets_path), YOUTUBE_UPLOAD_SCOPE)
        credentials = flow.run_local_server(port=0)
        token_path.parent.mkdir(parents=True, exist_ok=True)
        token_path.write_text(credentials.to_json(), encoding="utf-8")
        return credentials

    def validate_credentials(self) -> bool:
        """Validate existing local YouTube credentials without uploading or starting OAuth."""
        try:
            token_path = Path(self.settings.youtube_token_file)
            if not token_path.exists():
                return False
            credentials = Credentials.from_authorized_user_file(str(token_path), YOUTUBE_UPLOAD_SCOPE)
            if credentials.valid:
                return True
            if credentials.expired and credentials.refresh_token:
                credentials.refresh(Request())
                token_path.write_text(credentials.to_json(), encoding="utf-8")
                return credentials.valid
            return False
        except Exception:
            publish_logger.exception("YouTube credential validation failed")
            return False
