import json
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

from backend.config import get_settings
from services.utils.logging import get_rotating_logger
from services.utils.retry import retry
from services.youtube_oauth_service import YOUTUBE_OAUTH_SCOPES


publish_logger = get_rotating_logger("publish", "publish.log")
TRANSIENT_STATUS_CODES = {500, 502, 503, 504}


class YouTubeConfigurationError(Exception):
    """Raised when the local YouTube OAuth connection is missing or invalid."""


@dataclass(frozen=True)
class YouTubeUploadResult:
    youtube_video_id: str
    youtube_url: str
    thumbnail_url: str = ""
    published_at: str = ""
    upload_time: float = 0.0
    processing_status: str = "uploaded"
    progress: int = 100
    error: str = ""


class YouTubeService:
    """Upload videos to YouTube using the connected channel OAuth credentials."""

    def __init__(self) -> None:
        self.settings = get_settings()

    @retry(max_attempts=3, delays=(30, 120, 300), logger=publish_logger)
    def upload_video(
        self,
        video_path: str,
        title: str = "AI Short",
        description: str = "Generated by social-media-ai.",
        tags: list[str] | None = None,
        privacy_status: str = "private",
        thumbnail_path: str | None = None,
        category_id: str = "22",
        publish_at: str | None = None,
    ) -> YouTubeUploadResult:
        """Upload a video with resumable progress and optional thumbnail upload."""
        started_at = time.perf_counter()
        tags = tags or ["AI", "Shorts", "Automation"]
        publish_logger.info("YouTube upload started video_path=%s privacy=%s", video_path, privacy_status)
        youtube = self._build_client()
        body = self._video_body(
            title=title,
            description=description,
            tags=tags,
            category_id=category_id,
            privacy_status=privacy_status,
            publish_at=publish_at,
        )
        media = MediaFileUpload(video_path, chunksize=8 * 1024 * 1024, resumable=True, mimetype="video/mp4")
        request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
        response = self._execute_resumable_upload(request)
        youtube_video_id = str(response["id"])
        thumbnail_url = ""

        if thumbnail_path:
            if Path(thumbnail_path).exists():
                thumbnail_url = self._upload_thumbnail(youtube, youtube_video_id, thumbnail_path)
            else:
                publish_logger.warning("YouTube thumbnail missing path=%s video_id=%s", thumbnail_path, youtube_video_id)

        processing_status = self._processing_status(youtube, youtube_video_id)
        uploaded_at = datetime.now(timezone.utc).isoformat()
        result = YouTubeUploadResult(
            youtube_video_id=youtube_video_id,
            youtube_url=f"https://www.youtube.com/watch?v={youtube_video_id}",
            thumbnail_url=thumbnail_url,
            published_at=publish_at or uploaded_at,
            upload_time=round(time.perf_counter() - started_at, 3),
            processing_status=processing_status,
            progress=100,
        )
        publish_logger.info(
            "YouTube upload complete video_id=%s status=%s progress=%s upload_time=%.3fs",
            result.youtube_video_id,
            result.processing_status,
            result.progress,
            result.upload_time,
        )
        return result

    def _execute_resumable_upload(self, request: Any) -> dict[str, Any]:
        response = None
        while response is None:
            try:
                status, response = request.next_chunk()
                if status is not None:
                    progress = round(float(status.progress()) * 100)
                    publish_logger.info("YouTube upload progress=%s", progress)
            except HttpError as exc:
                if self._is_transient_error(exc):
                    publish_logger.warning(
                        "Transient YouTube upload error status=%s body=%s",
                        exc.resp.status,
                        self._http_error_body(exc),
                    )
                    raise
                publish_logger.exception("Non-retryable YouTube upload error body=%s", self._http_error_body(exc))
                raise
        if not isinstance(response, dict) or not response.get("id"):
            raise RuntimeError(f"YouTube upload returned an invalid response: {response}")
        return response

    def _upload_thumbnail(self, youtube: Any, youtube_video_id: str, thumbnail_path: str) -> str:
        try:
            media = MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
            youtube.thumbnails().set(videoId=youtube_video_id, media_body=media).execute()
            publish_logger.info("Uploaded YouTube thumbnail video_id=%s path=%s", youtube_video_id, thumbnail_path)
            return f"https://img.youtube.com/vi/{youtube_video_id}/maxresdefault.jpg"
        except Exception:
            publish_logger.exception("YouTube thumbnail upload failed video_id=%s", youtube_video_id)
            return ""

    def _processing_status(self, youtube: Any, youtube_video_id: str) -> str:
        try:
            response = youtube.videos().list(part="processingDetails,status", id=youtube_video_id).execute()
            items = response.get("items") or []
            if not items:
                return "uploaded"
            details = items[0].get("processingDetails") or {}
            return str(details.get("processingStatus") or items[0].get("status", {}).get("uploadStatus") or "uploaded")
        except Exception:
            publish_logger.exception("Unable to fetch YouTube processing status video_id=%s", youtube_video_id)
            return "unknown"

    def _build_client(self) -> Any:
        credentials = self._load_credentials()
        return build("youtube", "v3", credentials=credentials)

    def _load_credentials(self) -> Credentials:
        connection = self._load_connection()
        if not connection:
            raise YouTubeConfigurationError("YouTube channel is not connected")
        credentials = Credentials(
            token=connection.get("access_token"),
            refresh_token=connection.get("refresh_token"),
            token_uri="https://oauth2.googleapis.com/token",
            client_id=self.settings.google_oauth_client_id,
            client_secret=self.settings.google_oauth_client_secret,
            scopes=YOUTUBE_OAUTH_SCOPES,
        )
        expires_at = connection.get("expires_at")
        if isinstance(expires_at, (int, float)):
            credentials.expiry = datetime.fromtimestamp(expires_at, tz=timezone.utc).replace(tzinfo=None)
        if credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
            connection["access_token"] = credentials.token
            if credentials.expiry is not None:
                connection["expires_at"] = credentials.expiry.replace(tzinfo=timezone.utc).timestamp()
            self._write_connection(connection)
            publish_logger.info("YouTube upload credentials refreshed")
        if not credentials.valid:
            raise YouTubeConfigurationError("YouTube credentials are invalid")
        return credentials

    def _load_connection(self) -> dict[str, Any]:
        path = Path(self.settings.youtube_oauth_connection_file)
        if not path.exists():
            return {}
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            publish_logger.exception("Failed to read YouTube OAuth connection file")
            return {}
        return data if isinstance(data, dict) else {}

    def _write_connection(self, connection: dict[str, Any]) -> None:
        path = Path(self.settings.youtube_oauth_connection_file)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(connection, indent=2), encoding="utf-8")

    def _video_body(
        self,
        title: str,
        description: str,
        tags: list[str],
        category_id: str,
        privacy_status: str,
        publish_at: str | None,
    ) -> dict[str, Any]:
        status: dict[str, Any] = {
            "privacyStatus": privacy_status,
            "selfDeclaredMadeForKids": False,
        }
        if publish_at:
            status["publishAt"] = publish_at
            status["privacyStatus"] = "private"
        return {
            "snippet": {
                "title": title,
                "description": description,
                "tags": tags,
                "categoryId": category_id,
            },
            "status": status,
        }

    def _is_transient_error(self, exc: HttpError) -> bool:
        status = getattr(getattr(exc, "resp", None), "status", None)
        return status in TRANSIENT_STATUS_CODES

    def _http_error_body(self, exc: HttpError) -> str:
        content = getattr(exc, "content", b"")
        if isinstance(content, bytes):
            return content.decode("utf-8", errors="replace")
        return str(content)

    def validate_credentials(self) -> bool:
        """Validate existing local YouTube credentials without uploading."""
        try:
            self._load_credentials()
            return True
        except Exception:
            publish_logger.exception("YouTube credential validation failed")
            return False
