import json
import logging
from pathlib import Path

from sqlalchemy.orm import Session

from database.models import PublishJob, PublishJobStatus, SEO, Thumbnail, Video
from services.metadata_service import GenerationMetadataService
from services.publisher_decision_service import PublisherDecisionService
from services.viral_prediction_service import ViralPredictionService
from services.youtube_service import YouTubeService

logger = logging.getLogger(__name__)


class PublishVideoNotFoundError(Exception):
    def __init__(self, video_id: int) -> None:
        super().__init__(f"Video {video_id} was not found")
        self.video_id = video_id


class PublishVideoFileNotFoundError(Exception):
    def __init__(self, video_path: str) -> None:
        super().__init__(f"Video file {video_path} was not found")
        self.video_path = video_path


class PublisherAgent:
    def __init__(
        self,
        db: Session,
        youtube_service: YouTubeService,
        viral_prediction_service: ViralPredictionService | None = None,
        publisher_decision_service: PublisherDecisionService | None = None,
        metadata_service: GenerationMetadataService | None = None,
    ) -> None:
        self.db = db
        self.youtube_service = youtube_service
        self.viral_prediction_service = viral_prediction_service
        self.publisher_decision_service = publisher_decision_service
        self.metadata_service = metadata_service or GenerationMetadataService()

    def publish_youtube(self, video_id: int) -> PublishJob:
        video = self.db.get(Video, video_id)
        if video is None:
            logger.warning("Cannot publish because video_id=%s was not found", video_id)
            raise PublishVideoNotFoundError(video_id)

        if not Path(video.path).exists():
            logger.warning("Cannot publish because video file is missing: %s", video.path)
            raise PublishVideoFileNotFoundError(video.path)

        logger.info("Publishing video_id=%s to YouTube Shorts", video.id)
        try:
            content_package = self._content_package(video)
            if self.viral_prediction_service is not None:
                prediction = self.viral_prediction_service.predict(content_package)
                self.metadata_service.save_viral_prediction(video_id=video.id, result=prediction)
                content_package["viral_prediction"] = prediction.model_dump()
            if self.publisher_decision_service is not None:
                decision = self.publisher_decision_service.decide(content_package)
                self.metadata_service.save_publisher_decision(video_id=video.id, result=decision)
            seo = self._latest_seo(video)
            thumbnail = self._latest_thumbnail(video)
            result = self.youtube_service.upload_video(
                video_path=video.path,
                title=seo.title if seo else "AI Short",
                description=seo.description if seo else "Generated by social-media-ai.",
                tags=json.loads(seo.tags) if seo else ["AI", "Shorts", "Automation"],
                privacy_status="private",
                thumbnail_path=thumbnail.path if thumbnail else None,
            )
            self.metadata_service.save_youtube_upload(video_id=video.id, result=result)
            job = PublishJob(
                video_id=video.id,
                platform="youtube",
                youtube_video_id=result.youtube_video_id,
                youtube_url=result.youtube_url,
                status=PublishJobStatus.UPLOADED,
            )
            self.db.add(job)
            self.db.commit()
            self.db.refresh(job)
            logger.info("Published video_id=%s youtube_video_id=%s", video.id, job.youtube_video_id)
            return job
        except Exception as exc:
            self.db.rollback()
            logger.exception("YouTube publish failed for video_id=%s", video.id)
            self.metadata_service.save_youtube_upload_error(video_id=video.id, error=str(exc))
            job = PublishJob(
                video_id=video.id,
                platform="youtube",
                youtube_video_id=None,
                youtube_url=None,
                status=PublishJobStatus.FAILED,
            )
            self.db.add(job)
            self.db.commit()
            self.db.refresh(job)
            return job

    def _content_package(self, video: Video) -> dict:
        script = video.audio.script
        seo = self._latest_seo(video)
        thumbnail = self._latest_thumbnail(video)
        return {
            "topic": script.topic.title,
            "script": script.content,
            "video_path": video.path,
            "thumbnail_path": thumbnail.path if thumbnail else "",
            "seo": {
                "title": seo.title if seo else "",
                "description": seo.description if seo else "",
                "tags": seo.tags if seo else "[]",
                "hashtags": seo.hashtags if seo else "",
            },
            "competitor_analysis": self.metadata_service.load_research_intelligence(script.id),
            "fact_verification": self.metadata_service.load_fact_verification(script.id),
            "hook_intelligence": self.metadata_service.load_hook_intelligence(script.id),
            "script_score": self.metadata_service.load_script_quality(script.id).get("script_score"),
            "content_intelligence": self.metadata_service.load_content_intelligence(script.id),
            "thumbnail_intelligence": self.metadata_service.load_thumbnail_intelligence(video.id),
            "seo_intelligence": self.metadata_service.load_seo_intelligence(video.id),
            "viral_prediction": self.metadata_service.load_viral_prediction(video.id),
        }

    def _latest_seo(self, video: Video) -> SEO | None:
        return (
            self.db.query(SEO)
            .filter(SEO.video_id == video.id)
            .order_by(SEO.created_at.desc())
            .first()
        )

    def _latest_thumbnail(self, video: Video) -> Thumbnail | None:
        return (
            self.db.query(Thumbnail)
            .filter(Thumbnail.video_id == video.id)
            .order_by(Thumbnail.created_at.desc())
            .first()
        )
